apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: sf-practic
  name: nginx-sf
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.21.1-alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config
          mountPath: "/etc/nginx"
          readOnly: true
        - name: htpasswd
          mountPath: "/etc/auth/"
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: nginx-config
          items:
          - key: nginx.conf
            path: nginx.conf
      - name: htpasswd
        configMap:
          name: basicauth
          items:
          - key: htpasswd
            path: htpasswd
